version: 0.2


phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Build phase"
      - echo "Building the project"
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Running tests"
      #- npm test  
      - aws s3 cp ./build s3://my-bucket-name/ --recursive
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Post-Build completed successfully"